### PR TITLE
Manual checks

### LINKED ISSUE #11: Add the manual checks
- [x] ints, floats
- [x] string
- [x] single line comment
- [x] multi line comment

### PR DESCRIPTION
**Pull request by am-cid**
closes #11 

# new
1. `self._seek()` is a private function that searches for a string or a list of strings (in order) in front of or behind the current character.
    - It returns `True` if all are found, `False` otherwise. 
    - It can search in multi-lines but the dev must specify how many lines should `self._seek` traverse to find the string/s
        - default is integer 0 lines which is on the same line only
        - can pass the string "EOF" or "BOF" as the argument if the dev wants to seek for strings until the end or the beginning of the file
    - seek ignores whitespaces ` ` by default but the dev can specify to stop searching when a whitespace ` ` is encountered
___
2. `Error` is an Enum that stores values which have an error type and an error message
___
3. `GenericError` is a class like the previously named `Error` (now `DelimError`) that handles formatting errors based on arguments passed to it
    - it is designed to be more generic `DelimError` where it takes an `Error` enum value as it's first argument, already giving this class an error type and a message
    - `context` can also be passed which is just a string of additional information the dev might want to give
___
4. `Warn` is an Enum that stores values which have a warning type and a warning message
___
5. `IntFloatWarning` is a class like `GenericError` but for warnings
    - since this is a warning class, this should be used for when values may still be appended to `self._tokens` even though something is wrong
    - this is why it takes in a `temp_num` for the original number literal and `corrected_value` for the correction
        - examples of `temp_num -> corrected value` would be `0. -> 0.0`, `00015 -> 15`, `1.0000 -> 1.0`
    - besides those, this has the same functionality as GenericError
___
6. `GenericWarning` is a class like `IntFloatWarning` but more general
    - since this is a warning class, this should be used for when values may still be appended to `self._tokens` even though something is wrong
    - besides those, this has the same functionality as GenericError
___
7. `self._is_fwunc_or_cwass_name()` is a private function that checks starting from the current position if the next few set of characters until a delimiter is a fwunc or cwass name
    - parenthesis and datatype dash will be checked in front of the current character using `self._seek`
    - keyword `fwunc` and `cwass` will be checked behind the current character using `self._seek`
    - based on the presence/absence of the above 4, this function will either:
        - append to tokens if correct fwunc/cwass name
        - append to errors if some checks are missing
        - append to errors if wrong case of starting character (uppercase only for cwass names, lowercase for fwunc names)
        - skip the entire thing (don't move cursor) if didn't meet criteria above and let other checks handle this
___
8. `self._is_identifier()` is like `self._is_fwunc_or_cwass_name()` but for identifiers
    - catches errors for when identifiers start with numbers and/or has special characters
___
9. `self._peek_string_literal()` is like `self._peek` but instead of for reserved words, it's for string literals
    - `"i am a string literal"`
    - `"i am a string part start|`
    - `|i am a string part mid|`
    - `|i am a string part end"`
    - `"we are |string_name|, the combined |1+2| parts"`
___
10. `self._peek_int_float_literal` is (*you guessed it*) `like self._peek` but for ints and floats
    - implemented a functionality where if a number immediately follows a letter, this will call `self._is_fwunc_or_cwass_name()` then `self._is_identifier()` to append this to errors there
        - this is for invalid fwunc/cwass/identifier names that start with numbers so that we can show that error
        - `21aqua-senpai = "i am invalid"`~
        - catches errors for when there are multiple decimal points and numbers above the 10 digit limit
            - floats can have 20 digits: 10 digits before and after the decimal point
        - warns user if there are trailing zeroes for float (after the decimal point) and leading zeroes int and float (before the decimal point)
            - converts the value by removing trailing/leading zeroes from the number
        - if there are more than 10 digits after the decimal point, this will cut off anything above 10 digits and only keep the remaining, warn the user + show the change, then append to list of tokens
___

___
# changes
1. `DELIMS` is now a dictionary of sets (previously lists) for faster lookup times
2. modified `self._verify_delims` to accommodate the above change
3. renamed previously `Error` to `DelimError` since that only handles errors regarding wrong/missing delimiters
4. moved checking of identifiers from under `self._get_tokens()` to it's own private method `self._is_identifier()` which does the same thing but now can be called by other processes

### CODE REVIEW

**Review by Gidsss — APPROVED** [review]

**Comment by am-cid** [comment]
log from extensive test
```
sample text file
____________________
0 | channel-chan~
1 | channel
2 | fwunc channel-chan()
3 | fwunc channel()
4 | fwunc channel-chan[()
5 | channel-chan()
6 | chan~
7 | chan
8 | channel
9 |   21aqua-chan~
10 | aq_ua-chan~
11 | aqua6-chan = "AKUA AISHITEEE!"~
12 | "im an unterminated string"
13 | "unclosed string
14 | |what am I|a"~
15 | "hello |wo_rld| hello\|world"~ "hello\world|what|is this\|\|\|"~
16 | manji-senpai = "foo |aqua7 + shion| foo |ojou| boo"~
17 | 00010000000000000 + 5~
18 | 1.1.1~
19 | 1.111111111111110000000~
20 | 1111111111111111.1~
21 | 0.00~
22 | 1.~
23 | 6.0
24 | 8.00~
25 | 9.01~
26 | fwunc aqua-chan()
27 | fwunc aqua()
28 | fwunc aqua-chan
29 | aqua-chan()
30 | aqua()
31 | fwunc Shion-chan()
32 | fwunc Shion()
33 | fwunc Shion-chan
34 | Shionchan
35 | Shion()
36 | cwass Shion-chan()
37 | cwass Shion()
38 | cwass Shion-chan
39 | Shion-chan()
40 | Shion()
41 | cwass shion-chan()
42 | cwass shion()
43 | cwass shion-chan
44 | shion-chan()
45 | shion()
____________________
end of file

[UNTERMINATED IDENTIFIER] Error on line 1 column 7:
        expected any of these characters: < . & } > - % , ! ] / = [ ~ WHITESPACE * ) | +
        after channel but got NEWLINE instead

[MISSING DATATYPE] Error on line 3 from column 6 to 13:
        No data type was indicated on function declaration

[MISSING DATATYPE] Error on line 4 from column 14 to 17:
        No data type was indicated on function declaration

[MISSING FWUNC KEYWORD] Error on line 5 from column 0 to 6:
        Function declarations need to have a 'fwunc' before to indicate it is a function

[UNTERMINATED CHAN DATA TYPE] Error on line 7 column 4:
        expected any of these characters: = , ~ WHITESPACE ( )
        after chan but got NEWLINE instead

[UNTERMINATED IDENTIFIER] Error on line 8 column 7:
        expected any of these characters: < . & } > - % , ! ] / = [ ~ WHITESPACE * ) | +
        after channel but got NEWLINE instead

[INVALID START OF IDENTIFIER] Error on line 9 from column 2 to 7:
        identifiers can only start with lowercase/uppercase letters
        '21aqua' is invalid

[INVALID IDENTIFIER NAME] Error on line 10 from column 0 to 4:
        identifiers can only have alphanumeric characters
        'aq_ua' is invalid

[UNTERMINATED STRING LITERAL] Error on line 12 column 27:
        expected any of these characters: = , ! & ] [ WHITESPACE ~ } )
        after "im an unterminated string" but got NEWLINE instead

[UNCLOSED STRING] Error on line 13 from column 0 to 15:
        String literals should be closed with "
        '"unclosed string' is unclosed

[INVALID IDENTIFIER NAME] Error on line 14 from column 11 to 12:
        identifiers can only have alphanumeric characters
        'a"' is invalid

[INVALID IDENTIFIER NAME] Error on line 15 from column 8 to 13:
        identifiers can only have alphanumeric characters
        'wo_rld' is invalid

[LEADING ZEROES] Warning on line 17 from column 0 to 16:
        chan literals should not have leading zeroes
        value = '00010000000000000' --> corrected value = '10000000000000'

[OUT OF BOUNDS] Error on line 17 from column 0 to 16:
        chan and kun literals can only have up to 10 digits before and after the decimal (kun can have a max of 20 digits total)
        '10000000000000' is 14 digits long

[MULTIPLE DECIMAL POINT] Error on line 18 from column 0 to 4:
        kun literals can only have 1 decimal point
        '1.1.1' has 2 decimal points

[TRAILING ZEROES] Warning on line 19 from column 0 to 22:
        kun literals can have ONE trailing zero after the decimal point ONLY IF it's the only digit present (1.0)
        value = '1.111111111111110000000' --> corrected value = '1.11111111111111'

[OUT OF BOUNDS] Warning on line 19 from column 0 to 22:
        chan and kun literals can only have up to 10 digits before and after the decimal (kun can have a max of 20 digits total)
        '1.11111111111111' is 16 digits long after the decimal point

[OUT OF BOUNDS] Error on line 20 from column 0 to 17:
        chan and kun literals can only have up to 10 digits before and after the decimal (kun can have a max of 20 digits total)
        '1111111111111111.1' is 18 digits long

[TRAILING ZEROES] Warning on line 21 from column 0 to 3:
        kun literals can have ONE trailing zero after the decimal point ONLY IF it's the only digit present (1.0)
        value = '0.00' --> corrected value = '0.0'

[MISSING TRAILING ZERO] Warning on line 22 from column 0 to 1:
        kun literals should have digit/s present after the decimal point
        value = '1.' --> corrected value = '1.0'

[UNTERMINATED FLOAT LITERAL] Error on line 23 column 3:
        expected any of these characters: / = } ! < | + & ] ~ WHITESPACE - % > * )
        after 6.0 but got NEWLINE instead

[TRAILING ZEROES] Warning on line 24 from column 0 to 3:
        kun literals can have ONE trailing zero after the decimal point ONLY IF it's the only digit present (1.0)
        value = '8.00' --> corrected value = '8.0'

[MISSING DATATYPE] Error on line 27 from column 6 to 10:
        No data type was indicated on function declaration

[MISSING PARENTHESIS] Error on line 28 from column 6 to 9:
        No opening parenthesis was found on function declaration

[MISSING FWUNC KEYWORD] Error on line 29 from column 0 to 3:
        Function declarations need to have a 'fwunc' before to indicate it is a function

[INVALID FUNCTION NAME] Error on line 31 from column 6 to 10:
        Function names should only start with a lowercase letter
        invalid function name: Shion

[MISSING DATATYPE] Error on line 32 from column 6 to 11:
        No data type was indicated on class declaration

[MISSING PARENTHESIS] Error on line 33 from column 6 to 10:
        No opening parenthesis was found on class declaration

[MISSING DATATYPE] Error on line 37 from column 6 to 11:
        No data type was indicated on class declaration

[MISSING PARENTHESIS] Error on line 38 from column 6 to 10:
        No opening parenthesis was found on class declaration

[MISSING CWASS KEYWORD] Error on line 39 from column 0 to 4:
        Class declarations need to have a 'cwass' before to indicate it is a class

[INVALID CLASS NAME] Error on line 41 from column 6 to 10:
        Class names should only start with an uppercase letter
        invalid class name: shion

[MISSING DATATYPE] Error on line 42 from column 6 to 11:
        No data type was indicated on function declaration

[MISSING PARENTHESIS] Error on line 43 from column 6 to 10:
        No opening parenthesis was found on function declaration

[MISSING FWUNC KEYWORD] Error on line 44 from column 0 to 4:
        Function declarations need to have a 'fwunc' before to indicate it is a function



 ################################################################
       lexeme               token                 range
 _______________________________________________________________
|     channel      |     IDENTIFIER     |    (0, 0) - (0, 6)    |
|        -         |      ID_DELIM      |    (0, 7) - (0, 7)    |
|       chan       |   CHAN_DATA_TYPE   |   (0, 8) - (0, 11)    |
|        ~         |     TERMINATOR     |   (0, 12) - (0, 12)   |
|      fwunc       |   FWUNC_KEYWORD    |    (2, 0) - (2, 4)    |
|     channel      |   FUNCTION NAME    |   (2, 6) - (2, 12)    |
|        -         |      ID_DELIM      |   (2, 13) - (2, 13)   |
|       chan       |   CHAN_DATA_TYPE   |   (2, 14) - (2, 17)   |
|      fwunc       |   FWUNC_KEYWORD    |    (3, 0) - (3, 4)    |
|      fwunc       |   FWUNC_KEYWORD    |    (4, 0) - (4, 4)    |
|     channel      |   FUNCTION NAME    |   (4, 6) - (4, 12)    |
|        -         |      ID_DELIM      |   (4, 13) - (4, 13)   |
|        -         |      ID_DELIM      |    (5, 7) - (5, 7)    |
|       chan       |   CHAN_DATA_TYPE   |   (5, 8) - (5, 11)    |
|       chan       |   CHAN_DATA_TYPE   |    (6, 0) - (6, 3)    |
|        ~         |     TERMINATOR     |    (6, 4) - (6, 4)    |
|        -         |      ID_DELIM      |    (9, 8) - (9, 8)    |
|       chan       |   CHAN_DATA_TYPE   |   (9, 9) - (9, 12)    |
|        ~         |     TERMINATOR     |   (9, 13) - (9, 13)   |
|        -         |      ID_DELIM      |   (10, 5) - (10, 5)   |
|       chan       |   CHAN_DATA_TYPE   |   (10, 6) - (10, 9)   |
|        ~         |     TERMINATOR     |  (10, 10) - (10, 10)  |
|      aqua6       |     IDENTIFIER     |   (11, 0) - (11, 4)   |
|        -         |      ID_DELIM      |   (11, 5) - (11, 5)   |
|       chan       |   CHAN_DATA_TYPE   |   (11, 6) - (11, 9)   |
|"AKUA AISHITEEE!" |   STRING_LITERAL   |  (11, 13) - (11, 29)  |
|        ~         |     TERMINATOR     |  (11, 30) - (11, 30)  |
|   "what am I"    |  STRING_PART_MID   |  (14, 0) - (14, 10)   |
|        ~         |     TERMINATOR     |  (14, 13) - (14, 13)  |
|     "hello "     | STRING_PART_START  |   (15, 0) - (15, 7)   |
|  " hello|world"  |  STRING_PART_END   |  (15, 14) - (15, 28)  |
|        ~         |     TERMINATOR     |  (15, 29) - (15, 29)  |
|  "hello\\world"  | STRING_PART_START  |  (15, 30) - (15, 43)  |
|       what       |     IDENTIFIER     |  (15, 44) - (15, 47)  |
|   "is this|||"   |  STRING_PART_END   |  (15, 48) - (15, 62)  |
|        ~         |     TERMINATOR     |  (15, 63) - (15, 63)  |
|      manji       |     IDENTIFIER     |   (16, 0) - (16, 4)   |
|        -         |      ID_DELIM      |   (16, 5) - (16, 5)   |
|      senpai      |     IDENTIFIER     |  (16, 6) - (16, 11)   |
|      "foo "      | STRING_PART_START  |  (16, 15) - (16, 20)  |
|      aqua7       |     IDENTIFIER     |  (16, 21) - (16, 25)  |
|      shion       |     IDENTIFIER     |  (16, 29) - (16, 33)  |
|     " foo "      |  STRING_PART_MID   |  (16, 34) - (16, 40)  |
|       ojou       |     IDENTIFIER     |  (16, 41) - (16, 44)  |
|      " boo"      |  STRING_PART_END   |  (16, 45) - (16, 50)  |
|        ~         |     TERMINATOR     |  (16, 51) - (16, 51)  |
|        5         |    INT_LITERAL     |  (17, 20) - (17, 20)  |
|        ~         |     TERMINATOR     |  (17, 21) - (17, 21)  |
|        ~         |     TERMINATOR     |   (18, 5) - (18, 5)   |
| 1.11111111111111 |   FLOAT_LITERAL    |  (19, 0) - (19, 22)   |
|        ~         |     TERMINATOR     |  (19, 23) - (19, 23)  |
|        ~         |     TERMINATOR     |  (20, 18) - (20, 18)  |
|       0.0        |   FLOAT_LITERAL    |   (21, 0) - (21, 3)   |
|        ~         |     TERMINATOR     |   (21, 4) - (21, 4)   |
|       1.0        |   FLOAT_LITERAL    |   (22, 0) - (22, 1)   |
|        ~         |     TERMINATOR     |   (22, 2) - (22, 2)   |
|       8.0        |   FLOAT_LITERAL    |   (24, 0) - (24, 3)   |
|        ~         |     TERMINATOR     |   (24, 4) - (24, 4)   |
|       9.01       |   FLOAT_LITERAL    |   (25, 0) - (25, 3)   |
|        ~         |     TERMINATOR     |   (25, 4) - (25, 4)   |
|      fwunc       |   FWUNC_KEYWORD    |   (26, 0) - (26, 4)   |
|       aqua       |   FUNCTION NAME    |   (26, 6) - (26, 9)   |
|        -         |      ID_DELIM      |  (26, 10) - (26, 10)  |
|       chan       |   CHAN_DATA_TYPE   |  (26, 11) - (26, 14)  |
|      fwunc       |   FWUNC_KEYWORD    |   (27, 0) - (27, 4)   |
|      fwunc       |   FWUNC_KEYWORD    |   (28, 0) - (28, 4)   |
|        -         |      ID_DELIM      |  (28, 10) - (28, 10)  |
|       chan       |   CHAN_DATA_TYPE   |  (28, 11) - (28, 14)  |
|        -         |      ID_DELIM      |   (29, 4) - (29, 4)   |
|       chan       |   CHAN_DATA_TYPE   |   (29, 5) - (29, 8)   |
|       aqua       |   FUNCTION NAME    |   (30, 0) - (30, 3)   |
|      fwunc       |   FWUNC_KEYWORD    |   (31, 0) - (31, 4)   |
|        -         |      ID_DELIM      |  (31, 11) - (31, 11)  |
|       chan       |   CHAN_DATA_TYPE   |  (31, 12) - (31, 15)  |
|      fwunc       |   FWUNC_KEYWORD    |   (32, 0) - (32, 4)   |
|      fwunc       |   FWUNC_KEYWORD    |   (33, 0) - (33, 4)   |
|        -         |      ID_DELIM      |  (33, 11) - (33, 11)  |
|       chan       |   CHAN_DATA_TYPE   |  (33, 12) - (33, 15)  |
|    Shionchan     |     IDENTIFIER     |   (34, 0) - (34, 8)   |
|      Shion       |   CWASS_KEYWORD    |   (35, 0) - (35, 4)   |
|      cwass       |     IDENTIFIER     |   (36, 0) - (36, 4)   |
|      Shion       |   CWASS_KEYWORD    |  (36, 6) - (36, 10)   |
|        -         |      ID_DELIM      |  (36, 11) - (36, 11)  |
|       chan       |   CHAN_DATA_TYPE   |  (36, 12) - (36, 15)  |
|      cwass       |     IDENTIFIER     |   (37, 0) - (37, 4)   |
|      cwass       |     IDENTIFIER     |   (38, 0) - (38, 4)   |
|        -         |      ID_DELIM      |  (38, 11) - (38, 11)  |
|       chan       |   CHAN_DATA_TYPE   |  (38, 12) - (38, 15)  |
|        -         |      ID_DELIM      |   (39, 5) - (39, 5)   |
|       chan       |   CHAN_DATA_TYPE   |   (39, 6) - (39, 9)   |
|      Shion       |   CWASS_KEYWORD    |   (40, 0) - (40, 4)   |
|      cwass       |     IDENTIFIER     |   (41, 0) - (41, 4)   |
|        -         |      ID_DELIM      |  (41, 11) - (41, 11)  |
|       chan       |   CHAN_DATA_TYPE   |  (41, 12) - (41, 15)  |
|      cwass       |     IDENTIFIER     |   (42, 0) - (42, 4)   |
|      cwass       |     IDENTIFIER     |   (43, 0) - (43, 4)   |
|        -         |      ID_DELIM      |  (43, 11) - (43, 11)  |
|       chan       |   CHAN_DATA_TYPE   |  (43, 12) - (43, 15)  |
|        -         |      ID_DELIM      |   (44, 5) - (44, 5)   |
|       chan       |   CHAN_DATA_TYPE   |   (44, 6) - (44, 9)   |
|      shion       |   FUNCTION NAME    |   (45, 0) - (45, 4)   |
 _______________________________________________________________
```

**Comment by am-cid** [comment]
since I merged main into my branch, I'll start working on comments with no fear of conflict hell

**Review by Gidsss — APPROVED** [review]
yeah g

**Review by HolyShaq — APPROVED** [review]

**Comment by HolyShaq** [comment]
good stuff

**Review by chaaals — APPROVED** [review]

**Review by Gidsss — APPROVED** [review]

**Pull request merged**
