### PR TITLE
comments module

### PR DESCRIPTION
**Pull request by am-cid**
task 4/4 on #44 
3/5 subtasks of task 3 completed

> - [x] move_cursor.py
>     - `_advance` and `_reverse`
> - [x] verify_delim.py
> - [ ] peek.py
>     - [x] `_peek`
>     - [x] `_is_identifier`
>     - [ ] `_peek_string_literal`
>     - [ ] `_peek_int_float`
>     - [x] `_peek_comment_literal`
> - [x] seek.py

### CODE REVIEW

**Comment by am-cid** [comment]
log from test 
```
Running lexer package...

sample text file
____________________
1 | >//< this
2 | is
3 | a
4 | multiline
5 | comment
6 | >//<
7 | >.< single line comment
____________________
end of file



 ################################################################
       lexeme              token               range        
 _______________________________________________________________
|>//< this
is
a
multiline
comment
>//<| MULTI LINE COMMENT |    (0, 0) - (5, 3)    |
|>.< single line comment|      COMMENT       |   (6, 0) - (6, 23)    |
 _______________________________________________________________
```

**Review by Gidsss — COMMENTED** [review]
image

nakadikit siya sa GUI dun sa lexer table

**Comment by am-cid** [comment]
that's a gui problem, multi line comments have `\n`. the logs show that these two are two different comments. should I store the multiline comment as a raw string so `\n` will be printed out as part of the output lexeme?

**Comment by Gidsss** [comment]
Alright try ko fix and feel ko okay lang muna imerge etong PR since sa GUI part naman yun

**Pull request merged**
