### PR TITLE
Remove array info on lexer table

### PR DESCRIPTION
**Pull request by HolyShaq**
Changes:
- removes array info on lexeme and token info on our lexer table
- keeps parser in tact

### CODE REVIEW

**Review by am-cid — CHANGES_REQUESTED** [review]
using `.split('[')[0]` might be better here

**Comment by HolyShaq** [comment]
Smart. Asa biyahe nako tho, irefactor ko nlng sa school

**Comment by am-cid** [comment]
what I meant was not using `re` at all and just doing `.split('[')[0]` since `split()` is a safe operation (does not raise).
image

**Comment by HolyShaq** [comment]
ohhhhhhhhhhhh myb myb yea thats way better

**Comment by HolyShaq** [comment]
Actually, that may conflict with our double bracket tokens, no? It'd split it unless I make an exception for them

**Review by am-cid — APPROVED** [review]

**Pull request merged**
