### PR TITLE
Code format button

### PR DESCRIPTION
**Pull request by HolyShaq**
## Autoformatting in the editor!
- format button
- format option in right click context menu
- doesn't output lexer table and ast
- does output error logs if any
- !!!! New - custom console logs:
image
image

## Extra Changes
- changed tab space of the editor to 4 cuz that's what the formatting does
- proper comment auto formatting
- small class parsing bugfix
- refactored a bit of code in generate_log() method

## Extra Things to Maybe do
- Maybe change button logo, ginamit ko lang kasi ung isang png dun sa assets naten wahahha

### CODE REVIEW

**Review by am-cid — APPROVED** [review]

**Comment by chaaals** [comment]
Thanks @HolyShaq ! I'll test later, for extra things no. 2, we can maybe use this as reference since may access naman sa token positions? Basically add tayo squiggly lines sa text editor
https://stackoverflow.com/questions/61506470/is-it-possible-to-have-a-red-squiggly-line-appear-under-words-in-a-tkinter-text

**Comment by HolyShaq** [comment]
So may lalabas na squiggly line under every error found once na pindutin si format button? Also, I imagine na once we start modifying the text again, mawawala naung squiggly lines right?

**Comment by chaaals** [comment]
yep @HolyShaq, ayan yung navivisualize ko rn for handling formatting w/ errors

**Comment by HolyShaq** [comment]
Oki i like the idea, sounds good!

**Review by Gidsss — APPROVED** [review]

**Comment by Gidsss** [comment]
> Thanks @HolyShaq ! I'll test later, for extra things no. 2, we can maybe use this as reference since may access naman sa token positions? Basically add tayo squiggly lines sa text editor https://stackoverflow.com/questions/61506470/is-it-possible-to-have-a-red-squiggly-line-appear-under-words-in-a-tkinter-text

Hmu if need help @chaaals angas

**Review by chaaals — APPROVED** [review]
Thank u @HolyShaq !

**Pull request merged**
